-- Report ownership and unlisted-link sharing privacy (issue #22).
--
-- A Report generated by a signed-in user is now owned by them and private by
-- default; they may toggle it public, making it viewable by anyone with its
-- link (still unlisted — no gallery/directory). Anonymous Reports keep
-- today's behaviour unchanged: no owner, always public.
--
-- `source_repo_was_private` records whether the Target Repository was
-- private on GitHub at generation time. Combined with the check constraint
-- below, this makes "sourced from a private repo" and "publicly viewable"
-- mutually exclusive at the database layer itself — not only in application
-- code — so no future code path, present or future, can leak a private
-- repo's Report by making it public.

-- `is_public` is added with a `true` default so every existing row — all of
-- them anonymous Reports predating this migration — backfills correctly as
-- still-public. The default then flips to `false` below, so any future
-- insert that forgets to set it explicitly fails safe as private rather than
-- accidentally public; every current write path (saveReport) sets it
-- explicitly either way, so this is a safety net, not something app code
-- relies on.
alter table public.reports
  add column if not exists owner_id uuid references auth.users(id) on delete set null,
  add column if not exists is_public boolean not null default true,
  add column if not exists source_repo_was_private boolean not null default false;

alter table public.reports alter column is_public set default false;

alter table public.reports
  drop constraint if exists reports_private_source_not_public;
alter table public.reports
  add constraint reports_private_source_not_public
  check (not (source_repo_was_private and is_public));

create index if not exists reports_owner_id_idx on public.reports (owner_id);

-- Superseded: readable-by-everyone no longer holds once a Report can be owned
-- and private. A Report is now readable if it's public, or if the requester
-- is its owner — nothing else.
drop policy if exists "Reports are publicly readable" on public.reports;
create policy "Reports are publicly readable or owned"
  on public.reports for select
  using (is_public or auth.uid() = owner_id);

-- The one write a non-service-role client is allowed: an owner flipping their
-- own Report public. The check constraint above still applies to this path,
-- so a private-repo-sourced Report stays rejected regardless of who or what
-- attempts the update.
drop policy if exists "Owners can update their own report's visibility" on public.reports;
create policy "Owners can update their own report's visibility"
  on public.reports for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);
