#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# If something fails partway (set -e triggers), keep the window open long
# enough to actually read the error — otherwise a script launched by
# double-click/file-association just vanishes on exit, error and all.
trap 'ec=$?; printf "\n  %s✗ failed%s (exit %s) at line %s: %s\n" "$RED" "$RESET" "$ec" "$LINENO" "$BASH_COMMAND"; pause "Press Enter to close this window."; exit $ec' ERR

SUPABASE_PROJECT_REF="cscbbmytoyaorgkhereg"
SUPABASE_CLI="npx supabase"
MIGRATIONS_DIR="frontend/supabase/migrations"

banner "Migrate the real Supabase project (issue #22) — schema cutover"

# ── Stage 1: authenticate the CLI ──────────────────────────────────────────
stage "Supabase — get a personal access token and log in"
say "Everything so far (issue #22's ownership/RLS work) has only ever run"
say "against the local Supabase CLI stack, in dev and in CI. This wizard"
say "applies the same 5 migrations to the real hosted project instead:"
note "  https://${SUPABASE_PROJECT_REF}.supabase.co"
say ""
say "The CLI needs a personal access token to authenticate as you."
open_url "https://supabase.com/dashboard/account/tokens"
step "Click \"Generate new token\", name it something like \"repo-health-analyzer-cli\"."
step "Copy the token — Supabase shows it once."
ask_secret SUPABASE_ACCESS_TOKEN "Paste the access token:"
export SUPABASE_ACCESS_TOKEN
note "Not written to any file — exported for this run only. Re-run this wizard"
note "and paste it again next time; it isn't persisted to .env or GitHub."
say ""
say "Logging the CLI in with that token..."
if $SUPABASE_CLI login --token "$SUPABASE_ACCESS_TOKEN" >/dev/null 2>&1; then
  note "Logged in."
else
  warn "supabase login reported an error — continuing anyway; link (next) will"
  warn "fail loudly if the token was actually bad."
fi

# ── Stage 2: link the local project to the real one ────────────────────────
stage "Link this repo to the real Supabase project"
say "This points the local frontend/supabase/ CLI project at the hosted"
say "database instead of your local-only Docker stack. It does not change"
say "anything in the hosted project yet — that's Stage 3."
(
  cd frontend
  if $SUPABASE_CLI link --project-ref "$SUPABASE_PROJECT_REF"; then
    note "Linked to project ${SUPABASE_PROJECT_REF}."
  else
    warn "Link failed. Common cause: wrong/expired access token from Stage 1."
    exit 1
  fi
)
say ""
say "You'll be asked for the database password next — this is the Postgres"
say "password you set (or were shown) when the project was first created,"
say "not the access token from Stage 1."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/database"
note "If you don't have it handy, that page has a \"Reset database password\""
note "option — resetting it is fine, nothing else in this app stores it."

# ── Stage 3: push the migrations ────────────────────────────────────────────
stage "Push the 5 pending migrations to the real database"
say "These migrations create/alter tables on the hosted project. This is the"
say "one irreversible step in this wizard — review before continuing:"
for f in "$MIGRATIONS_DIR"/*.sql; do
  note "  - $(basename "$f")"
done
say ""
say "In order: reports table -> component scores -> component weights ->"
say "user_profiles (GitHub OAuth) -> report ownership + RLS policies."
if confirm "Push these to the live project ${SUPABASE_PROJECT_REF} now?"; then
  (
    cd frontend
    $SUPABASE_CLI db push
  )
  note "Migrations applied."
else
  warn "Skipped. Re-run this wizard (or 'cd frontend && ${SUPABASE_CLI} db push')"
  warn "whenever you're ready — Stages 1-2 already saved the link, so a re-run"
  warn "will only re-prompt for the access token."
fi

# ── Stage 4: verify RLS and the GitHub OAuth provider ───────────────────────
stage "Verify — RLS policies and GitHub OAuth provider"
say "Two things this repo's other setup steps depend on. Check both by hand:"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/editor"
step "Open the \"reports\" table -> the shield icon should show RLS enabled,"
step "with a SELECT policy scoped to is_public/owner and no anonymous INSERT."
step "Open the \"user_profiles\" table -> RLS enabled, SELECT policy is"
step "\"auth.uid() = id\", no INSERT/UPDATE policy for any client role."
if confirm "Do both tables show RLS enabled with those policies?"; then
  note "Schema cutover looks good."
else
  warn "If a table shows RLS disabled or policies missing, db push (Stage 3)"
  warn "may have partially failed — check its output above, or re-run it."
fi
say ""
say "Separately, ADR-0007 flags the GitHub OAuth provider (Client ID/Secret in"
say "Supabase Auth settings) as an external prerequisite this migration does"
say "NOT configure — it's a one-time dashboard setup, not a per-cutover step."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
if confirm "Does the GitHub provider already show as enabled here?"; then
  note "Good — login should work against the real project now."
else
  warn "Not set up yet. Run scripts/setup-github-oauth-supabase.sh separately"
  warn "to configure it — that wizard covers the GitHub OAuth App + Supabase"
  warn "provider + redirect URLs end to end."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
