#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

SUPABASE_PROJECT_REF="cscbbmytoyaorgkhereg"
SUPABASE_CALLBACK_URL="https://${SUPABASE_PROJECT_REF}.supabase.co/auth/v1/callback"

banner "GitHub OAuth login (issue #20) — Supabase provider setup"

# ── Stage 1: register a GitHub OAuth App ───────────────────────────────────
stage "GitHub — register an OAuth App"
say "This app is what Supabase uses to talk to GitHub on login."
say ""
say "One important thing up front: GitHub only ever redirects back to Supabase"
say "(never straight to our app), so this one GitHub App and its one redirect"
say "URL work for every environment at once — local dev AND your Vercel"
say "deployment. You will NOT register a second GitHub App for Vercel later;"
say "Stage 3 below is where the per-environment (localhost vs. Vercel) setup"
say "actually happens, on the Supabase side."
open_url "https://github.com/settings/applications/new"
note "If the page didn't open, paste that URL into your browser yourself."
say ""
step "Application name: anything recognizable, e.g. \"Repo Health Analyzer\"."
ask GITHUB_OAUTH_HOMEPAGE_URL "Homepage URL (cosmetic only — http://localhost:3000 is fine, or your Vercel URL if you have one already):"
say ""
warn "The field is labelled \"Redirect URI\" on GitHub's current form (it used"
warn "to say \"Authorization callback URL\" — same field). Paste this exact"
warn "value INTO that field — don't open it as a page, it's not a URL to visit:"
note "  $SUPABASE_CALLBACK_URL"
pause "Pasted it into the Redirect URI field? Press Enter to continue."
step "Click \"Register application\"."
step "On the app's page, copy the Client ID shown near the top."
ask GITHUB_OAUTH_CLIENT_ID "Paste the Client ID:"
step "Click \"Generate a new client secret\", then copy it — GitHub shows it once."
ask_secret GITHUB_OAUTH_CLIENT_SECRET "Paste the Client Secret:"
note "Not written to any file — it goes straight into Supabase in the next stage."

# ── Stage 2: enable the GitHub provider in Supabase ────────────────────────
stage "Supabase — enable the GitHub provider"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
step "Find \"GitHub\" in the provider list."
warn "Browsers sometimes autofill these fields with an unrelated saved value"
warn "(e.g. a database name) — clear whatever's already in Client ID / Client"
warn "Secret before typing, even if the toggle looks off."
step "Client ID: paste $GITHUB_OAUTH_CLIENT_ID"
step "Client Secret: paste the secret you copied in Stage 1."
step "Toggle GitHub ON, then click \"Save\"."
pause "Saved? Press Enter to continue."

# ── Stage 3: allow the redirect URL(s) — this is the per-environment step ──
stage "Supabase — allow each environment's redirect URL"
say "Our /auth/login route sends Supabase a redirectTo of \${origin}/auth/callback"
say "— so \"origin\" is localhost:3000 when you're testing locally, and your"
say "Vercel domain once it's deployed. Supabase only forwards to a redirect URL"
say "on its allow list below, and — unlike GitHub's single Redirect URI in"
say "Stage 1 — it accepts as many entries as you need, one per environment."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/url-configuration"
step "Under \"Redirect URLs\", add: http://localhost:3000/auth/callback"
say ""
if confirm "Do you already have a Vercel deployment URL to add too?"; then
  ask VERCEL_APP_URL "Your Vercel URL (e.g. https://your-app.vercel.app — no trailing slash):"
  step "Also add: ${VERCEL_APP_URL}/auth/callback"
  note "Deploying to a new/different Vercel URL later? Just come back to this same"
  note "Supabase page and add its /auth/callback too — no need to re-run Stage 1."
else
  note "No problem — add <your-vercel-url>/auth/callback here whenever you deploy."
  note "You won't need to touch GitHub's settings again to do it."
fi
step "Click \"Save\"."
pause "Saved? Press Enter to continue."

# ── Stage 4: verify ─────────────────────────────────────────────────────────
stage "Verify"
say "In the frontend/ directory, run: npm run dev"
say "Open http://localhost:3000 and click \"Log in with GitHub\" in the header."
say "Expected: GitHub's consent screen, not Supabase's \"provider is not enabled\" error."
if confirm "Did it reach GitHub's consent screen?"; then
  note "Login is wired up end to end."
else
  warn "Still broken — recheck: the Redirect URI in Stage 1 matches exactly (no"
  warn "trailing slash), Client ID/Secret really saved in Stage 2 (not stuck on"
  warn "autofilled text), and localhost redirect saved in Stage 3. Supabase"
  warn "provider settings can take a minute to propagate."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
